version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 14
    commands:
      # Install jq using yum instead of apt-get
      - yum update -y && yum install -y jq
      # Install Snyk CLI
      - npm install -g snyk

  pre_build:
    commands:
      # Get CodeArtifact authorization token with domain owner specified
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain my-package-domain --domain-owner 908027380341 --query authorizationToken --output text`
      - aws codeartifact login --tool pip --domain my-package-domain --domain-owner 908027380341 --repository my-packages

      # Set up twine credentials
      - export TWINE_USERNAME=aws
      - export TWINE_PASSWORD=$CODEARTIFACT_AUTH_TOKEN
      - export TWINE_REPOSITORY_URL=https://my-package-domain-908027380341.d.codeartifact.us-east-1.amazonaws.com/pypi/my-packages/

  build:
    commands:
      # Build your package
      - pip install wheel
      - python setup.py sdist bdist_wheel

      # Scan for vulnerabilities with Snyk
      - echo "Scanning for vulnerabilities with Snyk..."
      - snyk test --json > snyk-report.json || true

      # Check for critical or high vulnerabilities and fail the build if found
      - |
        if cat snyk-report.json | jq '.vulnerabilities[] | select(.severity == "critical" or .severity == "high")' | grep -q .; then
          echo "CRITICAL OR HIGH VULNERABILITIES FOUND! Pipeline terminated."
          cat snyk-report.json | jq '.vulnerabilities[] | select(.severity == "critical" or .severity == "high")'
          exit 1
        else
          echo "No critical or high vulnerabilities found. Proceeding with upload."
        fi

      # Upload to CodeArtifact with verbose output for debugging
      - pip install twine
      - python -m twine upload --verbose dist/*

      # Install SBOM generation tool
      - pip install cyclonedx-bom
      # Generate SBOM for your Python packages
      - cyclonedx-py environment -o sbom.json

      # Upload SBOM and vulnerability reports to S3
      - aws s3 cp sbom.json s3://my-pipeline-artifacts-908027380341/sbom-exports/
      - aws s3 cp snyk-report.json s3://my-pipeline-artifacts-908027380341/sbom-exports/snyk-report.json

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - dist/*
    - sbom.json
    - snyk-report.json