version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain my-package-domain --query authorizationToken --output text`
      - aws codeartifact login --tool pip --domain my-package-domain --repository my-packages
      - export TWINE_PASSWORD=$CODEARTIFACT_AUTH_TOKEN
      - rm -rf ~/.pypirc
      - echo "[distutils]" > ~/.pypirc
      - echo "index-servers = codeartifact" >> ~/.pypirc
      - echo "" >> ~/.pypirc
      - echo "[codeartifact]" >> ~/.pypirc
      - |
        echo "repository: https://my-package-domain-908027380341.d.codeartifact.us-east-1.amazonaws.com/pypi/my-packages/" >> ~/.pypirc
        echo "username: aws" >> ~/.pypirc
        echo "password: $CODEARTIFACT_AUTH_TOKEN" >> ~/.pypirc
  build:
    commands:
      - pip install twine
      - python setup.py sdist bdist_wheel
      - python -m twine upload --repository codeartifact dist/*
      # Trigger Amazon Inspector scan
      - aws inspector2 create-finding-aggregator
      - |
        SCAN_ID=$(aws inspector2 start-sbom-scan --resource-ids $CODEBUILD_BUILD_ARN --output text --query 'scanId')
        echo "Scan ID: $SCAN_ID"
        aws inspector2 get-sbom-scan-results --scan-id $SCAN_ID
  post_build:
    commands:
      - echo "Vulnerability scanning completed"

artifacts:
  files:
    - scan-results.json
